name: Tests and Linters

on: [ pull_request ]
jobs:
  tests-and-linters:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-22.04]

    steps:
#      - name: Install dependencies
#        run: sudo apt-get update && sudo apt-get install -y xvfb
      - name: Checkout Tempo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Install torch ğŸ•¯ï¸
        run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      - name: Install jax ğŸ§ 
        run: pip3 install "jax[cpu]==0.6.2"
      - name: Install python dependencies ğŸ”§
        run: pip install .[dev,envs]
      - name: Run linters ğŸ–Œï¸
        run: pre-commit run --all-files --verbose
      - name: Run tests ğŸ§ª
        run: pytest tests
#      - name: Run coverage
#        run: |
#          coverage html --directory=coverage_html_report
#          coverage report --fail-under=0.1
#      - name: Test build docs ğŸ“–
#        run: mkdocs build --verbose --site-dir docs_public

#TODO eventually add a stage to release
